### PR TITLE
Produce 'Roles' doc

### PR DESCRIPTION
**Pull request by cbeams**
Similar to the doc we already have on the [Proposals](https://docs.bisq.network/proposals.html) infrastructure and process, this doc on _Roles_ will capture everything about Roles infrastructure and process under the Bisq DAO.

It will:

 - [x] replace the proto-documentation we did for roles in the Phase Zero doc, particularly that found at https://docs.bisq.network/dao/phase-zero.html#bonded-contributor-roles
 - [x] capture the decisions we've made around roles in bisq-network/proposals#12 and bisq-network/proposals#13 and bisq-network/proposals#14
 - [x] document the way the https://github.com/bisq-network/roles repository works and document the responsibilities of the roles maintainer (bisq-network/roles#28).
 - [x] cover the relationship between role issues, GitHub teams, primary/secondary role owners
 - [x] document, or at least carve out a placeholder for documenting, the way bonding and BSQ interest payments will work for bonded contributor roles.
 - [x] document the process for creating a new role, which will likely involve submitting a _proposal_ for a new role, similar to the way [this one](https://github.com/bisq-network/proposals/issues/15) was done
 - [x] Update https://docs.bisq.network/dao/phase-zero.html#Appendix-A

### CODE REVIEW

**Comment by cbeams** [comment]
@bisq-network/role-owners, I have merged this new 'Roles' documentation without putting it through review because I will shortly put together two proposals that reference this doc, and those proposals will be an opportunity to provide feedback on the most important parts of it.

Of course, if you'd like to read and review the document in a standalone fashion, please do. Just add an issue or submit a pull request for any issues you encounter as you read through it. Also feel free to post questions and suggestions here on this pull request, even now that it is merged and closed. I'll still respond to them.

You can find the live version of the doc at https://docs.bisq.network/roles.html.

/cc @m52go

**Comment by m52go** [comment]
@cbeams just read through this, great doc. 

Only 1 suggestion: consider putting the 'Processes' section before 'The Roles Maintainer role'. The preceding sections discuss elements concerning all roles, the 'Role Maintainer' section only covers that one role, and then 'Processes' goes back to discussing elements that concern all roles. 

Switching the two would flow a bit better, I think, but up to you.

**Comment by m52go** [comment]
@cbeams just read through this, great doc.

Only 1 suggestion: consider putting the 'Processes' section before 'The Roles Maintainer role' section. The preceding sections discuss elements concerning all roles, the 'Role Maintainer' section only covers that one role, and then 'Processes' goes back to discussing elements that concern all roles.

I see why you did it this way, but switching the two would flow a bit better, I think.

**Comment by cbeams** [comment]
@m52go wrote:

> 1 suggestion: consider putting the 'Processes' section before 'The Roles Maintainer role' section.

Good call, I've just done this in https://github.com/bisq-network/bisq-docs/pull/77. Thanks!

**Pull request merged**
