### PR TITLE
[WIP] Getting Started Guide

### PR DESCRIPTION
**Pull request by m52go**
I probably went a little overboard for what's supposed to be an outline, but there's still plenty to do. I'm aware that the extra work I did is my own liability.

### CODE REVIEW

**Comment by m52go** [comment]
This commit was pretty horrible from a git perspective. I've cleaned everything up...updated old commit messages, set up signing, and made a new branch.

Looks like the only thing I can't do is update the branch on this PR. 

Should I just submit a new PR, since there's no discussion here yet about this PR content?

**Comment by cbeams** [comment]
Sure, @m52go, feel free to close this and issue a new pull request from your new branch. Before you do, though, make sure your new branch actually contains only the commits related to this doc. Notice above how there are commits from Bernard and me that have nothing to do with this doc? This is part of the reason that issuing pull requests from `master` is a bad idea. It ends up creating all kinds of chaos like this (I'll leave aside the details as to why this happens).

The easiest thing to do should be the following:

```
git checkout master
git fetch origin
git reset --hard origin/master
git checkout getting-started # or whatever your new branch name is
git rebase master
git log --oneline --decorate -10 # the only commits between `master` and `getting-started` should be your 6 commits related to this doc. If not, chat with me in Slack about it
git push --set-upstream m52go getting-started # push your pull request branch up to your remote
# re-issue the pull request from this new branch in the same way you did it the first time
```

If any of that doesn't work or doesn't make sense, just let me know.

**Comment by cbeams** [comment]
Also, please reference this pull request in the description of your new pull request, with a quick note as to why you created the new one, just for posterity.

**Comment by cbeams** [comment]
Also @m52go, when you create your new pull request, please reference https://github.com/bisq-network/bisq-docs/issues/37 in the description. Whenever you're creating a pull request that relates to some already existing issue, it's a good idea to link to it in this way, so that the pull request is discoverable from the original issue (the reference causes a link to the pull request to show up in the original issue's event timeline).

**Pull request closed without merging**
