### PR TITLE
Refine rules and dispute resolution

### PR DESCRIPTION
**Pull request by m52go**
Primary purposes:
- add trader chat rules
- add mediation to mentions of arbitration
- add details on mediators and arbitrator processes
- add more detail to existing rules

To complete #80.

[Preview this doc here](https://deploy-preview-167--bisq-docs.netlify.com/trading-rules.html).

### CODE REVIEW

**Comment by m52go** [comment]
Moved back to [WIP] since it should probably convey v1.2 trading rules at this point.

**Comment by m52go** [comment]
@bisq-network/arbitrators would you mind taking a look at this ["What to Expect" section](https://deploy-preview-167--bisq-docs.netlify.com/trading-rules.html#dispute-process-what-to-expect) of the arbitration part section and letting me know if it's accurate?

The guidelines I used to write that section were from an older doc...not sure if such procedures are used any more.

**Comment by m52go** [comment]
Moving back away from [WIP]...I think we should just merge this now to prevent further questions on mediation/arbitration in the interim until v1.2 is released. 

Will make v1.2 updates separately, and soon, so they're ready by the time of the release.

**Comment by m52go** [comment]
Just updated this PR for v1.2 since it hasn't been merged yet.

**Comment by ripcurlx** [comment]
I'm not sure if we have to mention this additionally, but we not only have the case where the Seller is a signer who could sign the Buyers account. There is also the case where the Buyer has a verified account and the Sellers account is signed after a successful trade as well. There is no extra warning in the app as there is no specific risk for both sides that the signing takes place.

> If the arbitrator sides with you, they will personally reimburse you (and probably take a small fee for their effort).

probably take a small fee sounds a little bit vague to me as a user. Although we say small fee it sounds like there is no limit to it. The fee probably is depending on who complicated the dispute resolution will be. Maybe we could think about limiting the fee somehow? (Max. the deposit of the loosing trading peer, or if there was just a technical error it could be a max percentage of the deposit). We haven't talked about this in much detail yet, but I'm not sure if should leave it as it is right now? @ManfredKarrer @sqrrm what do you think?

> Once a mediator or arbitrator has gathered enough evidence to make a decision, they will either suggest a payout (in the case of a mediator) or publish a new payout transaction (in the case of an arbitrator) from the 2-of-3 multisig deposit according to their findings.

There is still the 2-of-3 multisig deposit which won't exist anymore with 1.2.0

**Comment by sqrrm** [comment]
@ripcurlx I agree that 'probably' is not great. Much better to word it like you suggested with a scheme on how the fee is taken.

**Comment by m52go** [comment]
I've removed mention of fees altogether. Upon thinking about it...doesn't seem like a great idea for arbitrators to take fees out of payouts at all. It's a relatively small amount that will probably make already-disgruntled users more disgruntled.

Why not have arbitrators request fees when requesting reimbursement from the DAO?

If a user wins a payout case with an arbitrator, they've been found to not be at fault, so it seems strange to punish them. The guilty party is the one who should be charged...and their funds are inherent in the BSQ supply from which the arbitrator is getting reimbursed.

ripcurlx, sqrrm, @chimp1984...opinions welcome.

**Comment by ripcurlx** [comment]
> If a user wins a payout case with an arbitrator, they've been found to not be at fault, so it seems strange to punish them. The guilty party is the one who should be charged...and their funds are inherent in the BSQ supply from which the arbitrator is getting reimbursed.

If we have a guilty party than the fee can come from it's deposit. But if we have not guilty party, but a technical problem than there is no-one to be punished. So I do agree for the transitional phase until we have fixed the technical problems that we don't charge the users for arbitration. But that is just my personal opinion.

**Pull request merged**
