### PR TITLE
Implement pedromvpg's 2018 redesign

### PR DESCRIPTION
**Pull request by m52go**
It looks like the way AsciiDoc handles CSS is rather primitive. The best compromise I could find is to specify the CSS filename in `build.gradle` and then specifying the path to the file in every doc that needs it.

Ideally everything should only have to be configured in `build.gradle` with no per-doc markup necessary...but [docs in subdirectories cause path issues](http://discuss.asciidoctor.org/Single-CSS-for-multiple-nested-adoc-files-td552.html) and there's no clean solution.

@pedromvpg you suggested making the Bisq logo in the top-right a link to go home. I agree, but that side-menu seems auto-generated and I'm not sure how feasible it is to modify. For what it's worth, there's usually a 'Back' link that appears on all sub-pages so users can easily go back to the root/parent page.

### CODE REVIEW

**Comment by m52go** [comment]
> I expected the Bisq logo at the top left to take me back to https://bisq.network. Has that been considered?

Yes—that is the plan, but I'm currently not sure how the TOC is generated.

> If all docs live at the top level, then we can just move the :stylesdir: ./css attribute to build.gradle as well, so that it doesn't need to be repeated in every file like it is now.

Overriding would be better but I couldn't get it to work.

That's why I thought this might be the least worst way to proceed right now. But I'm assuming we want this design to be rolled out fairly soon (?). If it's still going to be a little while, I can try to flatten.

That's the ultimate goal which will not only fix this mess but also navigation and other stuff like default image directories (which faces the same issue as CSS).

**Comment by cbeams** [comment]
Ok, well, I don't want to hold up this pull request based on the `:stylesdir:` override. I'm not sure why it wouldn't "just work", but not a showstopper. I'll ACK this, but I guess we shouldn't actually merge it until we're ready for a coordinated launch with the main site / app / etc.

**Comment by m52go** [comment]
Hey @cbeams it turns out you have to explicitly indicate that you want global attributes to be overridable...file attributes don't override global attributes and that's apparently how it's supposed to work by default.

Corresponding with the lead developer of Asciidoc on their forum and he pointed me to the [entry in their docs that covers it](https://asciidoctor.org/docs/user-manual/#altering-the-attribute-assignment-precedence). 

Latest commit implements this fix.

**Comment by ManfredKarrer** [comment]
@m52go 
2 small things: The Bisq logo does not link back to the main page and the Doc string reight to it seems to have a diff. font...

**Comment by cbeams** [comment]
Nice 👍 

Dan is really helpful and Asciidoctor’s own docs are usually quite good too. Glad you figured it out (though I must say I find the solution unintuitive).

**Comment by m52go** [comment]
@ManfredKarrer I made the changes you mentioned (logo font + logo linking) in the most recent commits. I also added the new favicon.

An unintentional side effect of this change is that there are now 'back to index' links on every page including subdirectory docs. As a result, from a user's perspective, all docs now have consistent navigation links, which make the overall UX more cohesive. (Before subdirectory docs were detached from main docs, but that's not the case anymore).

**Pull request merged**
